<?php

/*
 *
 * List of All Currencies with Country Names
 * 
 */

$currencies = array(
  array('currency_id' => '1','currency_name' => 'Afghani','currency_code' => 'AFN'),
  array('currency_id' => '2','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '3','currency_name' => 'Lek','currency_code' => 'ALL'),
  array('currency_id' => '4','currency_name' => 'Algerian Dinar','currency_code' => 'DZD'),
  array('currency_id' => '5','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '6','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '7','currency_name' => 'Kwanza','currency_code' => 'AOA'),
  array('currency_id' => '8','currency_name' => 'East Caribbean Dollar','currency_code' => 'XCD'),
  array('currency_id' => '9','currency_name' => 'No universal currency','currency_code' => ''),
  array('currency_id' => '10','currency_name' => 'East Caribbean Dollar','currency_code' => 'XCD'),
  array('currency_id' => '11','currency_name' => 'Argentine Peso','currency_code' => 'ARS'),
  array('currency_id' => '12','currency_name' => 'Armenian Dram','currency_code' => 'AMD'),
  array('currency_id' => '13','currency_name' => 'Aruban Florin','currency_code' => 'AWG'),
  array('currency_id' => '14','currency_name' => 'Australian Dollar','currency_code' => 'AUD'),
  array('currency_id' => '15','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '16','currency_name' => 'Azerbaijanian Manat','currency_code' => 'AZN'),
  array('currency_id' => '17','currency_name' => 'Bahamian Dollar','currency_code' => 'BSD'),
  array('currency_id' => '18','currency_name' => 'Bahraini Dinar','currency_code' => 'BHD'),
  array('currency_id' => '19','currency_name' => 'Taka','currency_code' => 'BDT'),
  array('currency_id' => '20','currency_name' => 'Barbados Dollar','currency_code' => 'BBD'),
  array('currency_id' => '21','currency_name' => 'Belarussian Ruble','currency_code' => 'BYR'),
  array('currency_id' => '22','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '23','currency_name' => 'Belize Dollar','currency_code' => 'BZD'),
  array('currency_id' => '24','currency_name' => 'CFA Franc BCEAO','currency_code' => 'XOF'),
  array('currency_id' => '25','currency_name' => 'Bermudian Dollar','currency_code' => 'BMD'),
  array('currency_id' => '26','currency_name' => 'Ngultrum','currency_code' => 'BTN'),
  array('currency_id' => '27','currency_name' => 'Indian Rupee','currency_code' => 'INR'),
  array('currency_id' => '28','currency_name' => 'Boliviano','currency_code' => 'BOB'),
  array('currency_id' => '29','currency_name' => 'Mvdol','currency_code' => 'BOV'),
  array('currency_id' => '30','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '31','currency_name' => 'Convertible Mark','currency_code' => 'BAM'),
  array('currency_id' => '32','currency_name' => 'Pula','currency_code' => 'BWP'),
  array('currency_id' => '33','currency_name' => 'Norwegian Krone','currency_code' => 'NOK'),
  array('currency_id' => '34','currency_name' => 'Brazilian Real','currency_code' => 'BRL'),
  array('currency_id' => '35','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '36','currency_name' => 'Brunei Dollar','currency_code' => 'BND'),
  array('currency_id' => '37','currency_name' => 'Bulgarian Lev','currency_code' => 'BGN'),
  array('currency_id' => '38','currency_name' => 'CFA Franc BCEAO','currency_code' => 'XOF'),
  array('currency_id' => '39','currency_name' => 'Burundi Franc','currency_code' => 'BIF'),
  array('currency_id' => '40','currency_name' => 'Cabo Verde Escudo','currency_code' => 'CVE'),
  array('currency_id' => '41','currency_name' => 'Riel','currency_code' => 'KHR'),
  array('currency_id' => '42','currency_name' => 'CFA Franc BEAC','currency_code' => 'XAF'),
  array('currency_id' => '43','currency_name' => 'Canadian Dollar','currency_code' => 'CAD'),
  array('currency_id' => '44','currency_name' => 'Cayman Islands Dollar','currency_code' => 'KYD'),
  array('currency_id' => '45','currency_name' => 'CFA Franc BEAC','currency_code' => 'XAF'),
  array('currency_id' => '46','currency_name' => 'CFA Franc BEAC','currency_code' => 'XAF'),
  array('currency_id' => '47','currency_name' => 'Unidad de Fomento','currency_code' => 'CLF'),
  array('currency_id' => '48','currency_name' => 'Chilean Peso','currency_code' => 'CLP'),
  array('currency_id' => '49','currency_name' => 'Yuan Renminbi','currency_code' => 'CNY'),
  array('currency_id' => '50','currency_name' => 'Australian Dollar','currency_code' => 'AUD'),
  array('currency_id' => '51','currency_name' => 'Australian Dollar','currency_code' => 'AUD'),
  array('currency_id' => '52','currency_name' => 'Colombian Peso','currency_code' => 'COP'),
  array('currency_id' => '53','currency_name' => 'Unidad de Valor Real','currency_code' => 'COU'),
  array('currency_id' => '54','currency_name' => 'Comoro Franc','currency_code' => 'KMF'),
  array('currency_id' => '55','currency_name' => 'Congolese Franc','currency_code' => 'CDF'),
  array('currency_id' => '56','currency_name' => 'CFA Franc BEAC','currency_code' => 'XAF'),
  array('currency_id' => '57','currency_name' => 'New Zealand Dollar','currency_code' => 'NZD'),
  array('currency_id' => '58','currency_name' => 'Costa Rican Colon','currency_code' => 'CRC'),
  array('currency_id' => '59','currency_name' => 'CFA Franc BCEAO','currency_code' => 'XOF'),
  array('currency_id' => '60','currency_name' => 'Kuna','currency_code' => 'HRK'),
  array('currency_id' => '61','currency_name' => 'Peso Convertible','currency_code' => 'CUC'),
  array('currency_id' => '62','currency_name' => 'Cuban Peso','currency_code' => 'CUP'),
  array('currency_id' => '63','currency_name' => 'Netherlands Antillean Guilder','currency_code' => 'ANG'),
  array('currency_id' => '64','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '65','currency_name' => 'Czech Koruna','currency_code' => 'CZK'),
  array('currency_id' => '66','currency_name' => 'Danish Krone','currency_code' => 'DKK'),
  array('currency_id' => '67','currency_name' => 'Djibouti Franc','currency_code' => 'DJF'),
  array('currency_id' => '68','currency_name' => 'East Caribbean Dollar','currency_code' => 'XCD'),
  array('currency_id' => '69','currency_name' => 'Dominican Peso','currency_code' => 'DOP'),
  array('currency_id' => '70','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '71','currency_name' => 'Egyptian Pound','currency_code' => 'EGP'),
  array('currency_id' => '72','currency_name' => 'El Salvador Colon','currency_code' => 'SVC'),
  array('currency_id' => '73','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '74','currency_name' => 'CFA Franc BEAC','currency_code' => 'XAF'),
  array('currency_id' => '75','currency_name' => 'Nakfa','currency_code' => 'ERN'),
  array('currency_id' => '76','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '77','currency_name' => 'Ethiopian Birr','currency_code' => 'ETB'),
  array('currency_id' => '78','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '79','currency_name' => 'Falkland Islands Pound','currency_code' => 'FKP'),
  array('currency_id' => '80','currency_name' => 'Danish Krone','currency_code' => 'DKK'),
  array('currency_id' => '81','currency_name' => 'Fiji Dollar','currency_code' => 'FJD'),
  array('currency_id' => '82','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '83','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '84','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '85','currency_name' => 'CFP Franc','currency_code' => 'XPF'),
  array('currency_id' => '86','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '87','currency_name' => 'CFA Franc BEAC','currency_code' => 'XAF'),
  array('currency_id' => '88','currency_name' => 'Dalasi','currency_code' => 'GMD'),
  array('currency_id' => '89','currency_name' => 'Lari','currency_code' => 'GEL'),
  array('currency_id' => '90','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '91','currency_name' => 'Ghana Cedi','currency_code' => 'GHS'),
  array('currency_id' => '92','currency_name' => 'Gibraltar Pound','currency_code' => 'GIP'),
  array('currency_id' => '93','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '94','currency_name' => 'Danish Krone','currency_code' => 'DKK'),
  array('currency_id' => '95','currency_name' => 'East Caribbean Dollar','currency_code' => 'XCD'),
  array('currency_id' => '96','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '97','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '98','currency_name' => 'Quetzal','currency_code' => 'GTQ'),
  array('currency_id' => '99','currency_name' => 'Pound Sterling','currency_code' => 'GBP'),
  array('currency_id' => '100','currency_name' => 'Guinea Franc','currency_code' => 'GNF'),
  array('currency_id' => '101','currency_name' => 'CFA Franc BCEAO','currency_code' => 'XOF'),
  array('currency_id' => '102','currency_name' => 'Guyana Dollar','currency_code' => 'GYD'),
  array('currency_id' => '103','currency_name' => 'Gourde','currency_code' => 'HTG'),
  array('currency_id' => '104','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '105','currency_name' => 'Australian Dollar','currency_code' => 'AUD'),
  array('currency_id' => '106','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '107','currency_name' => 'Lempira','currency_code' => 'HNL'),
  array('currency_id' => '108','currency_name' => 'Hong Kong Dollar','currency_code' => 'HKD'),
  array('currency_id' => '109','currency_name' => 'Forint','currency_code' => 'HUF'),
  array('currency_id' => '110','currency_name' => 'Iceland Krona','currency_code' => 'ISK'),
  array('currency_id' => '111','currency_name' => 'Indian Rupee','currency_code' => 'INR'),
  array('currency_id' => '112','currency_name' => 'Rupiah','currency_code' => 'IDR'),
  array('currency_id' => '113','currency_name' => 'SDR (Special Drawing Right)','currency_code' => 'XDR'),
  array('currency_id' => '114','currency_name' => 'Iranian Rial','currency_code' => 'IRR'),
  array('currency_id' => '115','currency_name' => 'Iraqi Dinar','currency_code' => 'IQD'),
  array('currency_id' => '116','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '117','currency_name' => 'Pound Sterling','currency_code' => 'GBP'),
  array('currency_id' => '118','currency_name' => 'New Israeli Sheqel','currency_code' => 'ILS'),
  array('currency_id' => '119','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '120','currency_name' => 'Jamaican Dollar','currency_code' => 'JMD'),
  array('currency_id' => '121','currency_name' => 'Yen','currency_code' => 'JPY'),
  array('currency_id' => '122','currency_name' => 'Pound Sterling','currency_code' => 'GBP'),
  array('currency_id' => '123','currency_name' => 'Jordanian Dinar','currency_code' => 'JOD'),
  array('currency_id' => '124','currency_name' => 'Tenge','currency_code' => 'KZT'),
  array('currency_id' => '125','currency_name' => 'Kenyan Shilling','currency_code' => 'KES'),
  array('currency_id' => '126','currency_name' => 'Australian Dollar','currency_code' => 'AUD'),
  array('currency_id' => '127','currency_name' => 'North Korean Won','currency_code' => 'KPW'),
  array('currency_id' => '128','currency_name' => 'Won','currency_code' => 'KRW'),
  array('currency_id' => '129','currency_name' => 'Kuwaiti Dinar','currency_code' => 'KWD'),
  array('currency_id' => '130','currency_name' => 'Som','currency_code' => 'KGS'),
  array('currency_id' => '131','currency_name' => 'Kip','currency_code' => 'LAK'),
  array('currency_id' => '132','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '133','currency_name' => 'Lebanese Pound','currency_code' => 'LBP'),
  array('currency_id' => '134','currency_name' => 'Loti','currency_code' => 'LSL'),
  array('currency_id' => '135','currency_name' => 'Rand','currency_code' => 'ZAR'),
  array('currency_id' => '136','currency_name' => 'Liberian Dollar','currency_code' => 'LRD'),
  array('currency_id' => '137','currency_name' => 'Libyan Dinar','currency_code' => 'LYD'),
  array('currency_id' => '138','currency_name' => 'Swiss Franc','currency_code' => 'CHF'),
  array('currency_id' => '139','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '140','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '141','currency_name' => 'Pataca','currency_code' => 'MOP'),
  array('currency_id' => '142','currency_name' => 'Denar','currency_code' => 'MKD'),
  array('currency_id' => '143','currency_name' => 'Malagasy Ariary','currency_code' => 'MGA'),
  array('currency_id' => '144','currency_name' => 'Kwacha','currency_code' => 'MWK'),
  array('currency_id' => '145','currency_name' => 'Malaysian Ringgit','currency_code' => 'MYR'),
  array('currency_id' => '146','currency_name' => 'Rufiyaa','currency_code' => 'MVR'),
  array('currency_id' => '147','currency_name' => 'CFA Franc BCEAO','currency_code' => 'XOF'),
  array('currency_id' => '148','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '149','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '150','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '151','currency_name' => 'Ouguiya','currency_code' => 'MRO'),
  array('currency_id' => '152','currency_name' => 'Mauritius Rupee','currency_code' => 'MUR'),
  array('currency_id' => '153','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '154','currency_name' => 'ADB Unit of Account','currency_code' => 'XUA'),
  array('currency_id' => '155','currency_name' => 'Mexican Peso','currency_code' => 'MXN'),
  array('currency_id' => '156','currency_name' => 'Mexican Unidad de Inversion (UDI)','currency_code' => 'MXV'),
  array('currency_id' => '157','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '158','currency_name' => 'Moldovan Leu','currency_code' => 'MDL'),
  array('currency_id' => '159','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '160','currency_name' => 'Tugrik','currency_code' => 'MNT'),
  array('currency_id' => '161','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '162','currency_name' => 'East Caribbean Dollar','currency_code' => 'XCD'),
  array('currency_id' => '163','currency_name' => 'Moroccan Dirham','currency_code' => 'MAD'),
  array('currency_id' => '164','currency_name' => 'Mozambique Metical','currency_code' => 'MZN'),
  array('currency_id' => '165','currency_name' => 'Kyat','currency_code' => 'MMK'),
  array('currency_id' => '166','currency_name' => 'Namibia Dollar','currency_code' => 'NAD'),
  array('currency_id' => '167','currency_name' => 'Rand','currency_code' => 'ZAR'),
  array('currency_id' => '168','currency_name' => 'Australian Dollar','currency_code' => 'AUD'),
  array('currency_id' => '169','currency_name' => 'Nepalese Rupee','currency_code' => 'NPR'),
  array('currency_id' => '170','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '171','currency_name' => 'CFP Franc','currency_code' => 'XPF'),
  array('currency_id' => '172','currency_name' => 'New Zealand Dollar','currency_code' => 'NZD'),
  array('currency_id' => '173','currency_name' => 'Cordoba Oro','currency_code' => 'NIO'),
  array('currency_id' => '174','currency_name' => 'CFA Franc BCEAO','currency_code' => 'XOF'),
  array('currency_id' => '175','currency_name' => 'Naira','currency_code' => 'NGN'),
  array('currency_id' => '176','currency_name' => 'New Zealand Dollar','currency_code' => 'NZD'),
  array('currency_id' => '177','currency_name' => 'Australian Dollar','currency_code' => 'AUD'),
  array('currency_id' => '178','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '179','currency_name' => 'Norwegian Krone','currency_code' => 'NOK'),
  array('currency_id' => '180','currency_name' => 'Rial Omani','currency_code' => 'OMR'),
  array('currency_id' => '181','currency_name' => 'Pakistan Rupee','currency_code' => 'PKR'),
  array('currency_id' => '182','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '183','currency_name' => 'No universal currency','currency_code' => ''),
  array('currency_id' => '184','currency_name' => 'Balboa','currency_code' => 'PAB'),
  array('currency_id' => '185','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '186','currency_name' => 'Kina','currency_code' => 'PGK'),
  array('currency_id' => '187','currency_name' => 'Guarani','currency_code' => 'PYG'),
  array('currency_id' => '188','currency_name' => 'Nuevo Sol','currency_code' => 'PEN'),
  array('currency_id' => '189','currency_name' => 'Philippine Peso','currency_code' => 'PHP'),
  array('currency_id' => '190','currency_name' => 'New Zealand Dollar','currency_code' => 'NZD'),
  array('currency_id' => '191','currency_name' => 'Zloty','currency_code' => 'PLN'),
  array('currency_id' => '192','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '193','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '194','currency_name' => 'Qatari Rial','currency_code' => 'QAR'),
  array('currency_id' => '195','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '196','currency_name' => 'Romanian Leu','currency_code' => 'RON'),
  array('currency_id' => '197','currency_name' => 'Russian Ruble','currency_code' => 'RUB'),
  array('currency_id' => '198','currency_name' => 'Rwanda Franc','currency_code' => 'RWF'),
  array('currency_id' => '199','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '200','currency_name' => 'Saint Helena Pound','currency_code' => 'SHP'),
  array('currency_id' => '201','currency_name' => 'East Caribbean Dollar','currency_code' => 'XCD'),
  array('currency_id' => '202','currency_name' => 'East Caribbean Dollar','currency_code' => 'XCD'),
  array('currency_id' => '203','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '204','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '205','currency_name' => 'East Caribbean Dollar','currency_code' => 'XCD'),
  array('currency_id' => '206','currency_name' => 'Tala','currency_code' => 'WST'),
  array('currency_id' => '207','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '208','currency_name' => 'Dobra','currency_code' => 'STD'),
  array('currency_id' => '209','currency_name' => 'Saudi Riyal','currency_code' => 'SAR'),
  array('currency_id' => '210','currency_name' => 'CFA Franc BCEAO','currency_code' => 'XOF'),
  array('currency_id' => '211','currency_name' => 'Serbian Dinar','currency_code' => 'RSD'),
  array('currency_id' => '212','currency_name' => 'Seychelles Rupee','currency_code' => 'SCR'),
  array('currency_id' => '213','currency_name' => 'Leone','currency_code' => 'SLL'),
  array('currency_id' => '214','currency_name' => 'Singapore Dollar','currency_code' => 'SGD'),
  array('currency_id' => '215','currency_name' => 'Netherlands Antillean Guilder','currency_code' => 'ANG'),
  array('currency_id' => '216','currency_name' => 'Sucre','currency_code' => 'XSU'),
  array('currency_id' => '217','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '218','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '219','currency_name' => 'Solomon Islands Dollar','currency_code' => 'SBD'),
  array('currency_id' => '220','currency_name' => 'Somali Shilling','currency_code' => 'SOS'),
  array('currency_id' => '221','currency_name' => 'Rand','currency_code' => 'ZAR'),
  array('currency_id' => '222','currency_name' => 'No universal currency','currency_code' => ''),
  array('currency_id' => '223','currency_name' => 'South Sudanese Pound','currency_code' => 'SSP'),
  array('currency_id' => '224','currency_name' => 'Euro','currency_code' => 'EUR'),
  array('currency_id' => '225','currency_name' => 'Sri Lanka Rupee','currency_code' => 'LKR'),
  array('currency_id' => '226','currency_name' => 'Sudanese Pound','currency_code' => 'SDG'),
  array('currency_id' => '227','currency_name' => 'Surinam Dollar','currency_code' => 'SRD'),
  array('currency_id' => '228','currency_name' => 'Norwegian Krone','currency_code' => 'NOK'),
  array('currency_id' => '229','currency_name' => 'Lilangeni','currency_code' => 'SZL'),
  array('currency_id' => '230','currency_name' => 'Swedish Krona','currency_code' => 'SEK'),
  array('currency_id' => '231','currency_name' => 'WIR Euro','currency_code' => 'CHE'),
  array('currency_id' => '232','currency_name' => 'Swiss Franc','currency_code' => 'CHF'),
  array('currency_id' => '233','currency_name' => 'WIR Franc','currency_code' => 'CHW'),
  array('currency_id' => '234','currency_name' => 'Syrian Pound','currency_code' => 'SYP'),
  array('currency_id' => '235','currency_name' => 'New Taiwan Dollar','currency_code' => 'TWD'),
  array('currency_id' => '236','currency_name' => 'Somoni','currency_code' => 'TJS'),
  array('currency_id' => '237','currency_name' => 'Tanzanian Shilling','currency_code' => 'TZS'),
  array('currency_id' => '238','currency_name' => 'Baht','currency_code' => 'THB'),
  array('currency_id' => '239','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '240','currency_name' => 'CFA Franc BCEAO','currency_code' => 'XOF'),
  array('currency_id' => '241','currency_name' => 'New Zealand Dollar','currency_code' => 'NZD'),
  array('currency_id' => '242','currency_name' => 'Pa?anga','currency_code' => 'TOP'),
  array('currency_id' => '243','currency_name' => 'Trinidad and Tobago Dollar','currency_code' => 'TTD'),
  array('currency_id' => '244','currency_name' => 'Tunisian Dinar','currency_code' => 'TND'),
  array('currency_id' => '245','currency_name' => 'Turkish Lira','currency_code' => 'TRY'),
  array('currency_id' => '246','currency_name' => 'Turkmenistan New Manat','currency_code' => 'TMT'),
  array('currency_id' => '247','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '248','currency_name' => 'Australian Dollar','currency_code' => 'AUD'),
  array('currency_id' => '249','currency_name' => 'Uganda Shilling','currency_code' => 'UGX'),
  array('currency_id' => '250','currency_name' => 'Hryvnia','currency_code' => 'UAH'),
  array('currency_id' => '251','currency_name' => 'UAE Dirham','currency_code' => 'AED'),
  array('currency_id' => '252','currency_name' => 'Pound Sterling','currency_code' => 'GBP'),
  array('currency_id' => '253','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '254','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '255','currency_name' => 'US Dollar (Next day)','currency_code' => 'USN'),
  array('currency_id' => '256','currency_name' => 'Uruguay Peso en Unidades Indexadas (URUIURUI)','currency_code' => 'UYI'),
  array('currency_id' => '257','currency_name' => 'Peso Uruguayo','currency_code' => 'UYU'),
  array('currency_id' => '258','currency_name' => 'Uzbekistan Sum','currency_code' => 'UZS'),
  array('currency_id' => '259','currency_name' => 'Vatu','currency_code' => 'VUV'),
  array('currency_id' => '260','currency_name' => 'Bolivar','currency_code' => 'VEF'),
  array('currency_id' => '261','currency_name' => 'Dong','currency_code' => 'VND'),
  array('currency_id' => '262','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '263','currency_name' => 'US Dollar','currency_code' => 'USD'),
  array('currency_id' => '264','currency_name' => 'CFP Franc','currency_code' => 'XPF'),
  array('currency_id' => '265','currency_name' => 'Moroccan Dirham','currency_code' => 'MAD'),
  array('currency_id' => '266','currency_name' => 'Yemeni Rial','currency_code' => 'YER'),
  array('currency_id' => '267','currency_name' => 'Zambian Kwacha','currency_code' => 'ZMW'),
  array('currency_id' => '268','currency_name' => 'Zimbabwe Dollar','currency_code' => 'ZWL')
);
